### ISSUE TITLE
Create systemd unit file

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/captcha-lite#3]
Current deployment options that are available to be used by the users are Docker, Fly.io, and Heroku. What if they want to run it on their VM without any of that with minimal resource? They can use systemd. 

The task is very simple, just provide a systemd unit file with environment variables already loaded (and give notice for them to change it). Please take into account of the restart policy and it needs network connection.

**Comment by himanshus-dev** [comment]
Hey @aldy505 - I can add a systemd service file. Please assign this to me.
