### ISSUE TITLE
Console as logging option

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/captcha-lite#4]
Current logging uses noop, sentry, and rollbar. Provide console logger. Might use zerolog or similar, but make sure the library that's being used has minimal dependency (no dependency would be best).

**Comment by WahidinAji** [comment]
is it mean changing the Noop etc to Zerolog or adding Zerolog to one of them??

**Comment by falentio** [comment]
may I work with this feature, I will add zerolog if permitted

**Comment by aldy505** [comment]
@falentio Sure, go ahead
