### ISSUE TITLE
Provide Prometheus metrics

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/captcha-lite#5]
Provide a `/metrics` endpoints that can be used to monitor the application to Prometheus.

Some metrics that can be monitored:
- How many users that joined to the group (per group name) -- either just joined, finished, or didn't finished the captcha
- How many users that finished the captcha (per group name)
- How many users that didn't finish the captcha (per group name)
- How many users are donig the captcha right now (per group name)
- How many commands are the bot sending to Telegram (per group name) -- commands means everything from banning a user, deleting a message, and sending a message.

Can be enabled only by specifying `METRICS=true` on the environment variable.

**Comment by Iiqbal2000** [comment]
Bang ini kalau mau dapetin nama grupnya harus manggil method atau field apa ya?

**Comment by aldy505** [comment]
Cek ke dokumentasi Telebotnya aja.

**Comment by Iiqbal2000** [comment]
Ini metrik per nama grupnya diregister setelah botnya ditambahkan ke group gitu ya bang

**Comment by aldy505** [comment]
Metricnya nggak perlu per nama grup yang harus di registerin, cukup jenis metricsnya aja. Nanti nama grup nya bisa dijadiin additional metadata yang attached ke metric itu.
