### ISSUE TITLE
Upgrade Telebot dependency to v3

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/captcha-lite#9]
Reference: https://pkg.go.dev/gopkg.in/telebot.v3

Right now we're using Telebot v2, yet the original [teknologi-umum/captcha](https://github.com/teknologi-umum/captcha) repository uses Telebot v3. We shall upgrade to that version, too.

**Comment by himanshus-dev** [comment]
Hi @aldy505 - I can do this. Please assign this to me.
